### ISSUE TITLE
Ctrl + W shortcut is used by some console apps, this conflicts with the default keybinding.

### ISSUE THREAD

**Issue by EternityForest** [SquitchYT/Tess#12]
Closing the window without warning or any kind of confirmation prompt, even when a user program is running, does not seem like good default behavior.  In general there shouldn't be any easy-to-trigger, confirmationless, and irreversible shortcuts in a GUI app at all.

It should check whether a program other than the shell is running and issue a confirmation dialog in that case, or perhaps not even trigger at all when a program is running.

**Comment by SquitchYT** [comment]
Hello, I'm happy that you have suggestions for Tess.
Regarding to shortcut, in specially the one that close tab. If you have any suggestion to replace the default shortcut, say it. Nevertheless, you can change this shortcut in the Config Page. 

For the confirmation PopUp, it will be added in the next major Update (0.6.0).
