### ISSUE TITLE
Option to change fonts

### ISSUE THREAD

**Issue by YUKI2eN3e** [SquitchYT/Tess#14]
Is there any way to change fonts so that Oh-My-Posh can be used?

**Comment by Asthowen** [comment]
Hello, 

First of all, thank you for using Tess! To answer your question, it is indeed possible to change the font of Tess. You just have to go in the settings (CTRL + P), then in the category `Terminal`, and finally, in the parameter `Fonts` to add before all the others the name of your font followed by a `,`.

Have a nice day,
