### ISSUE TITLE
Missing Publisher in Add or Remove Programs

### ISSUE THREAD

**Issue by OfficialEsco** [SquitchYT/Tess#17]
Hey there! The installer is not setting the Publisher field in the `A`dd or `R`emove `P`rograms registry table (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Tess_is1`)
This means WinGet will not find a match as it uses the Publisher and DisplayName to find the package and the DisplayVersion to look for updates.

```
Name          : Tess
Publisher     :
Version       : 0.6.0
ProductCode   : Tess_is1
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Tess_is1
Uninstall     : winget uninstall --id "Tess_is1"
```

**Comment by SquitchYT** [comment]
Hello, thanks for posting this issue. It will be fixed in the next release, which is planned to be released in one or two weeks. I keep open this until it was released
Have a nice day!

**Comment by SquitchYT** [comment]
It was fixed with the latest release. Have a nice day!
