### ISSUE TITLE
GPG key import error

### ISSUE THREAD

**Issue by Sush-ruta** [SquitchYT/Tess#20]
Importing the GPG key for Tess Debian repository gives the following error:

```
# curl -s https://apt.tessapp.dev/key.gpg | gpg --dearmor | tee /usr/share/keyrings/tess.gpg > /dev/null
gpg: no valid OpenPGP data found.
```

OS: Ubuntu 22.04

**Comment by SquitchYT** [comment]
Hello, 
First of all, thanks for reporting this!
Waiting for the GPG key to be fixed, you can use the `debian` package available here https://github.com/SquitchYT/Tess/releases/download/0.6.1/tess_0.6.1-1_all.deb.
I will let you know when the key is fixed.
Have a nice day!

**Comment by SquitchYT** [comment]
Hello, I seem to be fixed. Hope it work for you. Have a nice day!

**Comment by K0-RR** [comment]
https://apt.tessapp.dev/key.gpg is dead again
