### ISSUE TITLE
Doesn't work with Git Bash on Windows

### ISSUE THREAD

**Issue by AmirSavand** [SquitchYT/Tess#8]
![image](https://user-images.githubusercontent.com/4629328/141959058-5f3112a5-7b22-41fe-8f95-6321c426870b.png)

**Comment by SquitchYT** [comment]
Hello, this bug will be fixed in the next release. Can you give me more details like your profil option if you want more help while waiting for the next release

**Comment by AmirSavand** [comment]
I created a profile and tried many values for the command like the path of the Git Bash `"C:\Program Files\Git\git-bash.exe"` or a command that opens it, nothing worked.

If there was an option to change the terminal to CMD or Git Bash it would be great so users don't have to manually add them because honestly, Powershell is terrible.

**Comment by SquitchYT** [comment]
Try with `C:\Program\ Files\Git\git-bash.exe` as profil command.

**Comment by SquitchYT** [comment]
Fixed with the new release. Have a good day
