### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by ClementForget** [SquitchYT/Tess#9]
Hey,

![image](https://user-images.githubusercontent.com/44141533/143243629-bd0d44fc-15a8-4cc8-9dd9-c9d9f5bb1225.png)

The menu on the left hide settings :)

I run Tess on a Pop os 21.04

**Comment by SquitchYT** [comment]
Hello,

In the next release this menu will be closed when opening. For the moment you can click on the cross on the top left.

Have a nice day,
